// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7I2lrLZ28tZaOgXUvz-kwXO9aRgD7WB0',
    appId: '1:945197358965:android:c10bc1b68d0fbce354fd3c',
    messagingSenderId: '945197358965',
    projectId: 't-helper-a0132',
    databaseURL: 'https://t-helper-a0132-default-rtdb.firebaseio.com',
    storageBucket: 't-helper-a0132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRcCknghsAQzfzNnDQlMx1Zw6a9HSqLE',
    appId: '1:945197358965:ios:2b0f890f9a11712f54fd3c',
    messagingSenderId: '945197358965',
    projectId: 't-helper-a0132',
    databaseURL: 'https://t-helper-a0132-default-rtdb.firebaseio.com',
    storageBucket: 't-helper-a0132.appspot.com',
    iosClientId: '945197358965-itrf7aveo05glqhqpjb86i9r8b9fj2sl.apps.googleusercontent.com',
    iosBundleId: 'com.yvcdev.app',
  );
}
